In [ ]:
# import standard libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#importing the datafrom github repo
data=pd.read_csv("https://raw.githubusercontent.com/jayanth9844/railway-optimization/5a899afa85f597eb20b3149f0643dec6fa27eecd/dataset.csv")

In [ ]:
data

Unnamed: 0 travelClass  bookingStatus  status1Day  status1Month  \
0               0          3A             21          28            12   
1               1          3A             14          63            -1   
2               2          3A             39          -1            -1   
3               3          3A             11          46             8   
4               4          3A             20          -1            -1   
...           ...         ...            ...         ...           ...   
53376       53376          SL             55          57            -1   
53377       53377          SL            228          64            -1   
53378       53378          SL              5          33             4   
53379       53379          SL            326          -1            -1   
53380       53380          SL             96          -1            60   

       status1Week  status2Days  labels  
0               14           15     0.0  
1               -1           -1     0.0  
2               -1           18     0.0  
3               -1           -1     0.0  
4                7           -1     0.0  
...            ...          ...     ...  
53376           -1           -1     0.0  
53377           -1           -1     0.0  
53378           -1           -1     0.0  
53379           -1          242     0.0  
53380           -1           -1     0.0  

[53381 rows x 8 columns]

In [ ]:
data.isna().sum()

Unnamed: 0       0
travelClass      0
bookingStatus    0
status1Day       0
status1Month     0
status1Week      0
status2Days      0
labels           0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53381 entries, 0 to 53380
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0     53381 non-null  int64  
 1   travelClass    53381 non-null  object 
 2   bookingStatus  53381 non-null  int64  
 3   status1Day     53381 non-null  int64  
 4   status1Month   53381 non-null  int64  
 5   status1Week    53381 non-null  int64  
 6   status2Days    53381 non-null  int64  
 7   labels         53381 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 3.3+ MB


In [ ]:
data.drop("Unnamed: 0",axis=1,inplace=True)

In [ ]:
data.head()

travelClass  bookingStatus  status1Day  status1Month  status1Week  \
0          3A             21          28            12           14   
1          3A             14          63            -1           -1   
2          3A             39          -1            -1           -1   
3          3A             11          46             8           -1   
4          3A             20          -1            -1            7   

   status2Days  labels  
0           15     0.0  
1           -1     0.0  
2           18     0.0  
3           -1     0.0  
4           -1     0.0

In [ ]:
data.columns

Index(['travelClass', 'bookingStatus', 'status1Day', 'status1Month',
       'status1Week', 'status2Days', 'labels'],
      dtype='object')

In [ ]:
#doing one labelencoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['travelClass']=le.fit_transform(data['travelClass'])

In [ ]:
data.head()

travelClass  bookingStatus  status1Day  status1Month  status1Week  \
0            3             21          28            12           14   
1            3             14          63            -1           -1   
2            3             39          -1            -1           -1   
3            3             11          46             8           -1   
4            3             20          -1            -1            7   

   status2Days  labels  
0           15     0.0  
1           -1     0.0  
2           18     0.0  
3           -1     0.0  
4           -1     0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53381 entries, 0 to 53380
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   travelClass    53381 non-null  int64  
 1   bookingStatus  53381 non-null  int64  
 2   status1Day     53381 non-null  int64  
 3   status1Month   53381 non-null  int64  
 4   status1Week    53381 non-null  int64  
 5   status2Days    53381 non-null  int64  
 6   labels         53381 non-null  float64
dtypes: float64(1), int64(6)
memory usage: 2.9 MB


In [ ]:
# splitting the data into x an y values
x=data.drop("labels",axis=1)
y=data["labels"]

In [ ]:
# to get max of every column
columns=data.columns

for col in columns:
  print(f"{col} max:{data[col].max}")

travelClass max:<bound method Series.max of 0        3
1        3
2        3
3        3
4        3
        ..
53376    5
53377    5
53378    5
53379    5
53380    5
Name: travelClass, Length: 53381, dtype: int64>
bookingStatus max:<bound method Series.max of 0         21
1         14
2         39
3         11
4         20
        ... 
53376     55
53377    228
53378      5
53379    326
53380     96
Name: bookingStatus, Length: 53381, dtype: int64>
status1Day max:<bound method Series.max of 0        28
1        63
2        -1
3        46
4        -1
         ..
53376    57
53377    64
53378    33
53379    -1
53380    -1
Name: status1Day, Length: 53381, dtype: int64>
status1Month max:<bound method Series.max of 0        12
1        -1
2        -1
3         8
4        -1
         ..
53376    -1
53377    -1
53378     4
53379    -1
53380    60
Name: status1Month, Length: 53381, dtype: int64>
status1Week max:<bound method Series.max of 0        14
1        -1
2        -1
3        -1
4       

In [ ]:
# giving more weight to the first 3 columns
data["travelClass"]=data["travelClass"]*3
data["bookingStatus"]=data["bookingStatus"]*3
data["status1Day"]=data["status1Day"]*3

In [ ]:
#split into train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,shuffle=True,random_state=42)

In [ ]:
data.head()

travelClass  bookingStatus  status1Day  status1Month  status1Week  \
0            9             63          84            12           14   
1            9             42         189            -1           -1   
2            9            117          -3            -1           -1   
3            9             33         138             8           -1   
4            9             60          -3            -1            7   

   status2Days  labels  
0           15     0.0  
1           -1     0.0  
2           18     0.0  
3           -1     0.0  
4           -1     0.0

In [ ]:
#importing  metrics
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

#importing the libraries
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
import xgboost as xgb

In [ ]:
#choosing the right model dictionary
models={
    "Logistic Regression":LogisticRegression(max_iter=1000),
    "Random Forest":RandomForestClassifier(),
    "Gradient Boosting":GradientBoostingClassifier(),
    "Support Vector Classifier":SVC(),
    "K-Nearest Neighbors":KNeighborsClassifier(),
    "Decision Tree":DecisionTreeClassifier(),
    "Naive Bayes":GaussianNB(),
    "XGBoost":xgb.XGBClassifier(use_label_encoder=False,eval_metric="mlogloss")
}

In [ ]:
#Loop through the model
for model_name,model in models.items():
  print(f"Training {model_name}")

  #training the model
  model.fit(x_train,y_train)

  #make prediction
  y_preds=model.predict(x_test)

  #evaluation metrics
  accuracy=accuracy_score(y_test,y_preds)
  precision=precision_score(y_test,y_preds)
  recall=recall_score(y_test,y_preds)
  f1=f1_score(y_test,y_preds)
  conf_matrix=confusion_matrix(y_test,y_preds)

  #print the metrics results
  print(f"Accuracy:{accuracy:.4f}")
  print(f"Precision:{precision:.4f}")
  print(f"Recall:{recall:.4f}")
  print(f"F1:{f1:.4f}")
  print(f"Confussion Matris:\n{conf_matrix}\n")

Training Logistic Regression
Accuracy:0.9482
Precision:0.8496
Recall:0.6913
F1:0.7624
Confussion Matris:
[[9237  157]
 [ 396  887]]

Training Random Forest
Accuracy:0.9616
Precision:0.8922
Recall:0.7740
F1:0.8289
Confussion Matris:
[[9274  120]
 [ 290  993]]

Training Gradient Boosting
Accuracy:0.9689
Precision:0.9818
Recall:0.7553
F1:0.8537
Confussion Matris:
[[9376   18]
 [ 314  969]]

Training Support Vector Classifier
Accuracy:0.9412
Precision:0.8373
Recall:0.6337
F1:0.7214
Confussion Matris:
[[9236  158]
 [ 470  813]]

Training K-Nearest Neighbors
Accuracy:0.9629
Precision:0.9095
Recall:0.7677
F1:0.8326
Confussion Matris:
[[9296   98]
 [ 298  985]]

Training Decision Tree
Accuracy:0.9510
Precision:0.8025
Recall:0.7857
F1:0.7940
Confussion Matris:
[[9146  248]
 [ 275 1008]]

Training Naive Bayes
Accuracy:0.7130
Precision:0.2870
Recall:0.9353
F1:0.4392
Confussion Matris:
[[6413 2981]
 [  83 1200]]

Training XGBoost


/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:02:48] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy:0.9691
Precision:0.9658
Recall:0.7701
F1:0.8569
Confussion Matris:
[[9359   35]
 [ 295  988]]



In [ ]:
models.items()

dict_items([('Logistic Regression', LogisticRegression(max_iter=1000)), ('Random Forest', RandomForestClassifier()), ('Gradient Boosting', GradientBoostingClassifier()), ('Support Vector Classifier', SVC()), ('K-Nearest Neighbors', KNeighborsClassifier()), ('Decision Tree', DecisionTreeClassifier()), ('Naive Bayes', GaussianNB()), ('XGBoost', XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_

In [ ]:
# feature contribution extraction
importance=model.feature_importances_

# to see importance of each feature
for col,importance in zip(x.columns,importance):
  print(f"Feature:{col},Importance:{importance}")

Feature:travelClass,Importance:0.026120329275727272
Feature:bookingStatus,Importance:0.010651934891939163
Feature:status1Day,Importance:0.4698537290096283
Feature:status1Month,Importance:0.3026324212551117
Feature:status1Week,Importance:0.12195570766925812
Feature:status2Days,Importance:0.06878592073917389


In [ ]:
# Custom loss function (logistic regression loss with feature importance weighting)
def weighted_logistic_loss(y_true, y_pred):
    weights = np.array([3, 3, 3, 1, 1, 1])  # More importance to first 3 features
    # Logistic loss function
    preds = 1.0 / (1.0 + np.exp(-y_pred))

    # Calculate gradient and hessian
    grad = preds - y_true
    hess = preds * (1.0 - preds)

    # Apply weights (you may want to modify how these weights are applied based on features)
    weighted_grad = grad * np.mean(weights)  # Applying the weight (averaging for simplicity)
    weighted_hess = hess * np.mean(weights)  # Apply the weight here too

    return weighted_grad, weighted_hess

# Train an XGBoost model using the custom loss function
model = xgb.XGBClassifier(objective=weighted_logistic_loss)
model.fit(x_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None,
              objective=<function weighted_logistic_loss at 0x79d24af3e560>, ...)

In [ ]:
 #evaluation metrics
accuracy=accuracy_score(y_test,y_preds)
precision=precision_score(y_test,y_preds)
recall=recall_score(y_test,y_preds)
f1=f1_score(y_test,y_preds)
conf_matrix=confusion_matrix(y_test,y_preds)

#print the metrics results
print(f"Accuracy:{accuracy:.4f}")
print(f"Precision:{precision:.4f}")
print(f"Recall:{recall:.4f}")
print(f"F1:{f1:.4f}")
print(f"Confussion Matris:\n{conf_matrix}\n")

Accuracy:0.9691
Precision:0.9658
Recall:0.7701
F1:0.8569
Confussion Matris:
[[9359   35]
 [ 295  988]]



In [ ]:
# feature contribution extraction
importance=model.feature_importances_

# to see importance of each feature
for col,importance in zip(x.columns,importance):
  print(f"Feature:{col},Importance:{importance}")

Feature:travelClass,Importance:0.037275172770023346
Feature:bookingStatus,Importance:0.016174592077732086
Feature:status1Day,Importance:0.4035866856575012
Feature:status1Month,Importance:0.33129024505615234
Feature:status1Week,Importance:0.1377108097076416
Feature:status2Days,Importance:0.07396251708269119
